2024-09-24 11:50:01,752 - INFO - Processando o arquivo: /home/nay/Documentos/Projetos/SteamDB-Analytics-Pipeline/data/raw/raw_steamdb_sales_20240922.csv
2024-09-24 11:50:01,760 - ERROR - Erro durante o processamento: Cannot save file into a non-existent directory: '/home/nay/Documentos/Projetos/SteamDB-Analytics-Pipeline/data/processed'
2024-09-24 12:50:01,944 - INFO - Processando o arquivo: /home/nay/Documentos/Projetos/SteamDB-Analytics-Pipeline/data/raw/raw_steamdb_sales_20240922.csv
2024-09-24 12:50:01,950 - ERROR - Erro durante o processamento: Cannot save file into a non-existent directory: '/home/nay/Documentos/Projetos/SteamDB-Analytics-Pipeline/data/processed'
Traceback (most recent call last):
  File "/home/nay/Documentos/Projetos/SteamDB-Analytics-Pipeline/scripts/processing.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
